Added Dates and updated docs
TuringLang/TuringCallbacks.jl pull request #13
Opened 2020-09-28 17:51 UTC by jlperla

The lack of `Dates` was causing trouble after your latest update.  I also changed the docs to reflect the new default naming convention, which is great!

2020-09-29 10:39 UTC, torfjelde requested changes
Thanks @jlperla ! I have left some comments on the changes to the documentation + I'll just pus the `Dates` fix immediately :+1:

2020-09-29 10:39 UTC, torfjelde commented on docs/src/index.md
> +(where on your system, you may have replaced `pip` with `pip3` and `python` with `python3`)
IMO it's better to go with `pip3` and `python3` as a default since even if you only have Python 3 installed, these are available, while `pip` and `python` is ambiguous. 
I.e. if we use `pip3` we don't need this comment at all:)

2020-09-29 10:39 UTC, torfjelde commented on docs/src/index.md
> +(or, on some platforms, `python -m tensorboard.main --logdir runs`)
Essentially the same as before: I prefer to provide a command that is (almost) guaranteed to do the right thing (even though it doesn't look as nice). Assuming that the user followed the installation process above, `python3 -m tensorboard.main` is guaranteed to work, while `tensorboard` isn't.

Or am I misunderstanding something?

2020-09-29 10:39 UTC, torfjelde commented on docs/src/index.md
> +You will need an installation of `tensorboard` in Python (which **does not** require tensorflow to be installed).
A couple of things here. The plan is for `TuringCallbacks` to be more than _just_ a callback for TensorBoard. That's why I explicitly put all the tensorboard-related stuff (which, at the time, is everything that is in this package:) ) in a separate section. And I'd prefer to keep it that way :+1:

2020-09-29 10:39 UTC, torfjelde commented on docs/src/index.md
> +To actually visualize the results of the logging, you need to have installed
This line is incomplete (I'm guessing you were going to remove it?).

But I think I prefer the original formulation, simple because it emphasizes that installing `tensorboard` is completely optional. You can run use `TensorBoardLogger` without `tensorboard` installed, hence I want to convey that it's only necessary for visualization, not logging.

2020-09-29 10:39 UTC, torfjelde commented on docs/src/index.md
> +
Maybe just combine this with the comment on the `comment` keyword argument you added above, e.g.:



In addition, you can use the keyword arguments `directory` and `comment` to log to a different directory and adding a small comment to the the particular run:
```julia
# Logs to `new-runs/run-1`
callback = TensorBoardCallback(directory = "new-runs/run-1") 
# Logs to `runs/$(Dates.format(now(), dateformat"Y-m-d_H-M-S"))-$(gethostname())-num-adapts=$(num_adapts)`
callback = TensorBoardCallback(comment = "-num-adapts=$(num_adapts)") 
```
Note that `directory` completely overrides the `comment`, hence specifying `comment` if `directory` is specified has no effect.

2020-09-29 16:19 UTC, jlperla commented
Thank @torfjelde   Essentially I was doing on the python stuff was making it fully consistent with the tensorboard and tensorboard for pytorch docs.   For example, https://tensorboard.dev/#get-started and https://pytorch.org/docs/stable/tensorboard.html  and virtually every other thing on the internet.

Your instructions didn't work for me, so I had to modify them.  Maybe you have setup your python without using conda/etc.?  My guess is that anyone who needs installation instructions will be using conda or a similar system.

... but this is your package.  Do as you like.  I don't have strong opinions except just trying to copy what other people have done with beginner instructions and python.

2020-09-29 16:20 UTC, jlperla commented on docs/src/index.md
> +(where on your system, you may have replaced `pip` with `pip3` and `python` with `python3`)
It isn't ambiguous the way most people have things setup.  e.g. a conda installation or, even better a virtual environment!

I only left this one in for you, and think we are better off without any reference to `pip3` or `python3` etc.  Anyone not using conda can probable figure it out.

2020-09-29 16:21 UTC, jlperla commented on docs/src/index.md
> +(or, on some platforms, `python -m tensorboard.main --logdir runs`)
It didn't work for me without modifying the text, and it is inconsistent with all of the other tensorboard docs out there on the internet.  e.g. https://pytorch.org/docs/stable/tensorboard.html  and others.

2020-09-29 16:23 UTC, jlperla commented on docs/src/index.md
> +You will need an installation of `tensorboard` in Python (which **does not** require tensorflow to be installed).
Sounds good to me.  The issue was that it didn't separate out an installation step with a "visualization" step.  Not a big deal, but when there is an installation step I usually think of doing all the installations at the same time.  So having a sub-heading for tensorboard in Getting Started might help.

2020-09-29 16:24 UTC, jlperla commented on docs/src/index.md
> +To actually visualize the results of the logging, you need to have installed
Sounds good.  Modify as you see fit!

2020-09-29 16:24 UTC, jlperla commented on docs/src/index.md
> +
Sounds good, modify as you see fit!

2020-09-29 16:26 UTC, jlperla commented
@torfjelde   Can I suggest that you modify the doc as you see fit, or toss out all of my changes if you don't like them, and then merge?  I don't think we need to discuss it further, as you can modify the way you like it.  The only thing I wanted to get across in my repsonses was that I think you have a different python setup than most introductory people would, especially given that people frequently use conda and (hopefully!) are using virtual environments whenever possible.  python is impossible otherwise.

Later you might want to install tensorboard with `Conda.jl` if people have it installed.

2020-10-07 16:16 UTC, torfjelde commented
> The only thing I wanted to get across in my repsonses was that I think you have a different python setup than most introductory people would

And thank you for bringing this to my attention! I thought what I had written up was the lowest common denominator for the different setups, but it indeed seems like it's not the case. I'll likely keep a lot of what you added :+1:

2020-10-07 16:27 UTC, jlperla commented
@torfjelde  Sounds great.  But don't feel obligated.  I could be wrong :-)

Would love it for the package to be registreed sooner than later, which makes it easier to add as a package dependency.

2020-10-14 18:03 UTC, jlperla commented
The documetnation updates here are not cruciail, but is it possible to make this into a registered package?  It is otherwise hard to use as a dependency for packages.

2020-11-11 16:08 UTC, torfjelde commented
Just a heads up @jlperla ; it's registered now:) Sorry about the delay.

2020-11-11 16:14 UTC, jlperla commented
Great, thanks!

2021-06-09 17:29 UTC, closed without merging